### ISSUE TITLE
Clicking link (post form-submission) to go to /family-days doesn't take you to family-days page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchjr-website#116]
To repro, submit the form at `/outreach/host`, then click the link that says "https://scratchjr.org/outreach/host/family-days".

<img width="886" alt="screen shot 2017-10-10 at 1 32 15 pm" src="https://user-images.githubusercontent.com/1320456/31401638-853cb490-adc1-11e7-8652-c7091c6ef7c0.png">

**Comment by chrisgarrity** [comment]
Actually there were two issues. One is that the form links to the production website (as it should), but since it's still on staging, the page isn't there yet. So the website goes to the home page instead as expected. The other issue is that the page is loaded in the embedded iframe, not the top window or a separate tab, so it ends up as a page within a page:![Screen Shot 2017-10-10 at 1.59.47 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/6fb8fc3a-19be-4383-bb09-9e89b4e242d2/Screen+Shot+2017-10-10+at+1.59.47+PM.png)


I've submitted a PR for this: https://github.com/LLK/scratchjr-website/pull/117

**Comment by chrisgarrity** [comment]
I'll need to change the link in the Google form for testing.

**Comment by jwzimmer** [comment]
@chrisgarrity, can you verify if this is working as expected?

1) I see the link text `scratchjr.org/familydays` after I submit the form, although the standalone page URL is `scratchjr.org/outreach/host/family-days` (+ on Staging). Is that link text the correct link text?

2) When I submit the form I don't get taken to the standalone page `/outreach/host/family-days`, instead I see that page's contents loaded in the page but the URL `/outreach/host`. Is that correct?
I'm not sure how https://github.com/LLK/scratchjr-website/pull/117 is supposed to make the page load, other than **not** like it appears in https://github.com/LLK/scratchjr-website/issues/116#issuecomment-335796618.

**Standalone page**

**Not-standalone-page (after submitting form)**
<img width="991" alt="screen shot 2017-11-02 at 3 46 19 pm" src="https://user-images.githubusercontent.com/1320456/32346829-105726f2-bfe5-11e7-994c-5d7fd9ed7f9e.png">
<img width="953" alt="screen shot 2017-11-02 at 3 46 11 pm" src="https://user-images.githubusercontent.com/1320456/32346831-107758aa-bfe5-11e7-84f3-0fd138056a42.png">

**Comment by chrisgarrity** [comment]
Unfortunately this is the new 'expected' behavior. The Google form is embedded in an iframe. When the person clicks the link after submitting the form, it loads the link in the iframe (not the window). There is no way to tell google load this link in a separate tab or window. If we load the 'correct' page, you end up with a page within a page, as shown above.

To work-around this Google form limitation, I created a new version of the family-days content with no 'wrapping'. That is the one that is loaded after submitting the form, and it doesn't change the url because it loads in the iframe. The real page is still at the usual URL - that's the link that we would send to anyone if we want them to get to the family-days content.
